network:
  version: 2
  ethernets:
    enp1s0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.1/24
      routes:
        - to: default
          via: 192.168.1.1
          metric: 100
